# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

version: '3.7'
services:
  materialized:
    image: materialize/materialized:v0.12.0
    ports:
      - 6875:6875
    command: -w4 --disable-telemetry
    volumes:
      - minio:/data

  server:
    build: ./apps
    init: true
    ports:
      - 5000:5000
    volumes:
      - minio:/data
    command: /bin/sh -c "./server.py 2> /data/logfile/requests"

  client:
    build: ./apps
    init: true
    depends_on: [server]
    command: ./loadgen.py

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    entrypoint: sh
    command: -c 'mkdir -p /data/logfile && minio server /data --console-address=:9001'
    environment:
      - "MINIO_ACCESS_KEY=EXAMPLEKEYHERE"
      - "MINIO_SECRET_KEY=EXAMPLESECRETKEYHERE"

  mzcli:
    image: materialize/cli
    container_name: mzcli
    init: true
    depends_on:
      - materialized

volumes:
  minio:
