# Copyright Materialize, Inc. and contributors. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

version: '3.7'
services:
  materialized:
    image: materialize/materialized:v0.9.11
    ports:
      - 6875:6875
    command: -w4 --disable-telemetry
    volumes:
      - logfile:/log

  server:
    build: ./apps
    init: true
    ports:
      - 5000:5000
    volumes:
      - logfile:/log
    command: /bin/sh -c "./server.py 2> /log/requests"

  client:
    build: ./apps
    init: true
    depends_on: [server]
    command: ./loadgen.py

  mzcli:
    image: materialize/cli
    container_name: mzcli
    init: true
    depends_on:
      - materialized

volumes:
  logfile:
